version: '3.8'

services:
  server:
    container_name: resumer-server
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    ports:
      - '80:8000'
    env_file:
      - .env
