FROM node:20-alpine

RUN apk add --update --no-cache python3 make g++ py3-pip biber texlive-full
RUN npm i -g nodemon

WORKDIR /server

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

CMD [ "node", "index.js" ]