version: '3.8'

services:
  server:
    build: .
    ports:
      - '80:8000'
    environment:
      PORT: ${PORT}
      DB_URI: ${DB_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID}
