name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          sudo docker image rm resurer-server
          sudo docker build -t resumer-server .
          sudo docker compose pull
          sudo docker compose down
          sudo docker compose up -d
